version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: areed145/kk6gpv:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet: